apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels: 
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod # this name label is matched with pod template below for replica
  template:
    metadata:
      labels:
        name: mongo-pod #one of pod template lable
        app: todoapp #another lable for the pod template
    spec:
      containers:
      - name: mongo-container
        image: mongo:5.0
        resources:
        ports:
        - containerPort: 27017
        volumeMounts: 
          - name: mongo-storage
            mountPath: "/data/db"
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim