apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-vol
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual # we will create a hostpath volume, thus the volume class will be MANUAL 
  hostPath: 
    path: "/home/ubuntu/pv-data"