apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: todoapp
  type: NodePort # to be accessible from outside
  ports:
  - port: 30001 # port of the service in the cluster
    targetPort: 3000 # port of the pods/containers
    nodePort: 30001 # port of the service on node to be accessible outside
